[package]
name = "ydlidar_example"
version = "0.1.0"
edition = "2021"
default-run = "ydlidar_example"

[dependencies]
ydlidar-rust-driver = { path = ".." }
serialport = "4.7.2"

[[bin]]
name = "ydlidar_example"
path = "src/main.rs"

[[bin]]
name = "debug"
path = "src/debug_main.rs"